container:
  image: gradle:jdk8

check_task:
  gradle_cache:
    folder: ~/.gradle/caches
  check_script: ./gradlew check
  cleanup_before_cache_script:
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
