#!/bin/sh

set -e

CMD=$(basename $0)

bazel build //src/main/java/com/baulsupp/oksocial:oksocial-main >/dev/null 2>/dev/null || echo "Build failed" >&2


JAVA_CMD=java
BCP=

if [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

  if [ $? -eq 0 ]; then
    JAVA_CMD="$JAVA_HOME/bin/java"
    ALPN=$(ls target/alpn/alpn-boot-*.jar)
    BCP="-Xbootclasspath/p:$ALPN"
  fi
fi

bazel-bin/src/main/java/com/baulsupp/oksocial/oksocial-main "--jvm_flags=$BCP" --jvm_flag=-Dcommand.name=$CMD "$@"
