java_test(
  name = 'TwitterTestSuite',
  srcs = glob([
    '*.java'
  ]),
  resources = ['//src/test/resources'],
  deps = [
    '//src/main/java/com/baulsupp/oksocial',
    '//:com_squareup_okhttp3_okhttp',
    '//:junit_junit',
  ],
)
