junit_tests(
  name='oksocial',
  dependencies = [
  	'src/main/java/com/baulsupp/oksocial',
  	'3rdparty/jvm:junit',
  	'3rdparty/jvm:okhttp-testing-support',
  	'3rdparty/jvm:okhttp',
  ],
  sources=rglobs('*.java'),
  resources=['src/test/resources'],
)
